### ISSUE TITLE
Import Issue in Runtime Bindings

### ISSUE THREAD

**Issue by AmeanAsad** [fiberplane/fp-bindgen#161]
Hello! 

### Background: 

In the generated runtime bindings, there is a [line](https://github.com/fiberplane/fp-bindgen/blob/f57856589f416a06d3fa1b8e86218f1e3dfad6c0/fp-bindgen/src/generators/rust_wasmer_runtime/mod.rs#L368)  that uses the `Singlepass` import from wasmer as such:
`Store::new(wasmer_compiler_singlepass::Singlepass::default())`

### Issue:
-  `wasmer_compiler_singlepass` is not imported from wasmer, so this results in an error. 
- I think the expected behavior is to just import `Singlepass` directly from wasmer and use it.

**Comment by AmeanAsad** [comment]
I actually have a pull request to fix this. I followed th contributing guidelines -> created a new branch locally and tried to push to that but getting a `permission denied` for my github account.

**Comment by arendjr** [comment]
Fixed with #162.
