### ISSUE TITLE
function prologues cannot exceed 255 bytes in size for Windows x64

### ISSUE THREAD

**Issue by kajacx** [fiberplane/fp-bindgen#171]
I wanted to follow the examples as described in the readme. The protocol and plugin examples worked fine, but the wasmer runtime example gave me the following error at runtime for every single test:

thread '<unnamed>' panicked at 'function prologues cannot exceed 255 bytes in size for Windows x64', C:\Programs\Cargo\bin\registry\src\github.com-1ecc6299db9ec823\wasmer-compiler-singlepass-2.3.0\src\unwind_winx64.rs:303:9

Full paste with backtrace enabled: https://pastebin.com/1kqaA2je

Not sure what to do, googling this doesn't seem to find anything useful.

**EDIT:**
Removing all async functions from the protocol (and plugin and runtime, of course), makes the rest of the tests run fine.

**EDIT 2:**
Async in of itself isn't the problem. A simple String async import export example works fine. I will continue searching for the *specific* thing that is causing this problem.

**CONCLUSION:**
The problem is fixed in wasmer3, see [this issue](https://github.com/wasmerio/wasmer/issues/3559).

OS: Windows 10 64 bit
Rust version: rustc 1.66.1 (90743e729 2023-01-10)

**Comment by kajacx** [comment]
Ok, I tried to re-create the examples but remove everything except the primitive bindings, and it worked! I even managed to add another example that goes back and forth (none of the included examples seen to do that unfortunately): https://github.com/kajacx/fp-bindgen/commit/3018b65be82e050281af623ddf136210bd9ab563 but that is unrelated to this issue.

I can go and starting adding stuff one by one to find out what breaks it. My guess is that one of the more complicated types has too long function signature, but I'm not an expert on these things.

**Comment by arendjr** [comment]
Thanks for the report. I'd be curious to hear what breaks it indeed, though none of us are on Windows, so it will be hard for us to assist you unfortunately. I can attest however that we have significantly more complex bindings for our product than the ones provided in the examples, and we have never seen an issue such as this on other platforms.

FWIW, there's one existing example that tests back and forth async communication, which is the `fetch_data()` function: https://github.com/kajacx/fp-bindgen/blob/main/examples/example-plugin/src/lib.rs#L340

**Comment by sagacity** [comment]
I have a Windows machine I can use to take a quick look.

**Comment by sagacity** [comment]
It looks like there's an `unwind` feature that is present in the singlepass and cranelift compilers, but the feature is not exposed to us so we can't disable it.

We'll have to see if somehow the 255 byte restriction can be lifted or if wasmer can enable some sort of fallback path in which unwind info is not generated (although that does make debugging more difficult).

**Comment by kajacx** [comment]
Ok, it looks like the asynch methods are the problem. After removing `import_fp_struct`, `make_http_request`, `export_async_struct` and `fetch_data` from the protocol, the plugin and the runtime tests, the rest of the tests run fine. See the commit: https://github.com/kajacx/fp-bindgen/commit/dcdd443c4b6a357cc4021412cb057f311bc9b5db

Also, with those in, all tests fail, even those that run fine if those async bindings do not exists. And they fail at runtime. It's like the other function cannot even be called because the async functions are messing up the bindings or something?

**Comment by sagacity** [comment]
Perhaps you can see what happens if you add an 'empty' async function (i.e. one that doesn't really depend on any of the types you have just removed)?

**Comment by kajacx** [comment]
> Perhaps you can see what happens if you add an 'empty' async function (i.e. one that doesn't really depend on any of the types you have just removed)?

Yes, that's exactly what I did. Oh boy, was that a joy ride. TLDR: Primitive types don't really work with Futures.

First, if you use an async function in the protocol that return any primitive (including the empty tuple) other than u64, then you cannot compile the plugin because of the following error:

```
async fn import_u32_async() -> u32; // Example of added imported function

:\Programming\Rust\fp-bindgen-simple-example\examples\example-protocol\bindings\rust-plugin\src\import.rs:123:1
    |
123 | #[fp_bindgen_support::fp_import_signature]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | expected `u64`, found `u32`
    | arguments to this function are incorrect
    |
note: associated function defined here
   --> E:\Programming\Rust\fp-bindgen-simple-example\fp-bindgen-support\src\guest\async\mod.rs:26:19
    |
26  |     pub unsafe fn new(async_value_ptr: FatPtr) -> Self {
    |                   ^^^
    = note: this error originates in the attribute macro `fp_bindgen_support::fp_import_signature` (in Nightly builds, run with -Z macro-backtrace for more info)
help: you can convert a `u32` to a `u64`
    |
123 | #[fp_bindgen_support::fp_import_signature].into()
    |                                           +++++++
```

Next, if you do add an async import function that returns an u64, then the implementation in the runtime can return anything and it compiles file!. It can return nothing (empty tuple), u64, a different primitive or a complex data type (I tried String), and all compiles. The function still needs to be there, so it's not like it's being ignored, it can just return anything.

The exports are also wierd when it comes to returning primitive types from async functions. Returning non-u64 primitives gives the same error as with import functions when compiling the plugin, but returning u64 gives this new error when compiling the runtime:

```
async fn export_u64_async() -> u64; // Exported async function returning u64

error[E0308]: mismatched types
   --> src\spec\bindings.rs:883:67
    |
883 |         let result = result.map(|ref data| deserialize_from_slice(data));
    |                                            ---------------------- ^^^^ expected slice `[u8]`, found `u64`
    |                                            |
    |                                            arguments to this function are incorrect
    |
    = note: expected reference `&[u8]`
               found reference `&u64`
note: function defined here
   --> E:\Programming\Rust\fp-bindgen-simple-example\fp-bindgen-support\src\host\mem.rs:18:8
    |
18  | pub fn deserialize_from_slice<'a, T: Deserialize<'a>>(slice: &'a [u8]) -> T {
    |        ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src\spec\bindings.rs:896:12
    |
896 |         Ok(result)
    |         -- ^^^^^^ expected `u64`, found struct `Vec`
    |         |
    |         arguments to this enum variant are incorrect
    |
    = note: expected type `u64`
             found struct `Vec<u8>`
note: tuple variant defined here
   --> C:\Programs\Rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\result.rs:508:5
    |
508 |     Ok(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^

error[E0308]: mismatched types
   --> src\wasi_spec\bindings.rs:886:67
    |
886 |         let result = result.map(|ref data| deserialize_from_slice(data));
    |                                            ---------------------- ^^^^ expected slice `[u8]`, found `u64`
    |                                            |
    |                                            arguments to this function are incorrect
    |
    = note: expected reference `&[u8]`
               found reference `&u64`
note: function defined here
   --> E:\Programming\Rust\fp-bindgen-simple-example\fp-bindgen-support\src\host\mem.rs:18:8
    |
18  | pub fn deserialize_from_slice<'a, T: Deserialize<'a>>(slice: &'a [u8]) -> T {
    |        ^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src\wasi_spec\bindings.rs:899:12
    |
899 |         Ok(result)
    |         -- ^^^^^^ expected `u64`, found struct `Vec`
    |         |
    |         arguments to this enum variant are incorrect
    |
    = note: expected type `u64`
             found struct `Vec<u8>`
```

Ok, so that's primitive types. Complex types seem to work fine both ways, I tried importing and exporting String, all compiles fine, at runtime the functions are called correctly and return data as expected. Calling the `import_u64_async` function when the runtime implementation returns something else just hangs the test, but if it return u64 it works correctly. Funilly enough, it seems to work fine if it return u8, u16 or u32 as well.

I tried to make commit at logical points along my journey, you can see them here: https://github.com/kajacx/fp-bindgen/commits/async-functions-return-types

I guess all of that is not really related to my initial problem. Should I start a new issue and copy this entire description there? Finally, I will continue digging into what causes the "255 prologue" by making the used types increasingly more complicated until I reach the original example.

**Comment by sagacity** [comment]
Thanks for doing the digging @kajacx ! I would recommend you create a new issue for the async primitive problem, so we can leave this issue for the prologue error.

**Comment by kajacx** [comment]
Ok, turns out that replacing the body of the exported `fetch_data` function fixes the issue as well:

```rust
#[fp_export_impl(example_bindings)]
async fn fetch_data(r#type: String) -> Result<String, String> {
    Ok(r#"status: "confirmed"#.to_string())
}
```

Full commit: https://github.com/kajacx/fp-bindgen/commit/4dcde0e1a9655702d525a8280df68a26b2b9edab

I don't know if this has something to do with the size of the signature of the function (the future could be quite big), but it's something coming from wasmer:

```rust
// wasmer/lib/compiler-singlepass/src/unwind_winx64.rs

fn ensure_unwind_offset(offset: u32) -> Option<u8> {
    if offset > 255 {
        panic!("function prologues cannot exceed 255 bytes in size for Windows x64");
    }
    Some(offset as u8)
}
```

It would be interesting to try and use a different compiler than `singlepass` though.

**Comment by kajacx** [comment]
The problem is fixed with the wasmer3 port, see https://github.com/wasmerio/wasmer/issues/3559
