### ISSUE TITLE
Imported functions get passed zero when called with a float argument?

### ISSUE THREAD

**Issue by kajacx** [fiberplane/fp-bindgen#180]
**Description:**
I tried to pass float values around, but it look like an imported function (implemented in the host) receives zero instead of the value it was called with from the plugin if the value type is `f32` or `f64`.

**Example:**
```rust
// Protocol imports
fn import_add_two_f32(arg: f32) -> f32;

// Protocol exports
fn export_add_five_f32(arg: f32) -> f32;

// Plugin implementation
fn export_add_five_f32(arg: f32) -> f32 {
    import_add_two_f32(arg) + 3.0
}

// Host implementation
fn import_add_two_f32(arg: f32) -> f32 {
    arg + 2.0
}

// Host usage / test
assert_eq!(rt.export_add_five_f32(8.0)?, 13.0);
```

**The error:**
Instead of the expected `8.0 + 2.0 + 3.0 == 15.0`, you get just `5.0`. The error message actually says it is a different value every time:

```
    Assertion is failing with random values on the left. 3 runs gave 3 different values:
    left: `5.0`,
    left: `7.4971466`,
    left: `60.949524`,

    Full error:
    ---- test::primitives stdout ----
    Provider log: src\lib.rs:369: Example plugin initialized
    thread 'test::primitives' panicked at 'assertion failed: `(left == right)`
      left: `5.0`,
     right: `13.0`', src\test.rs:38:5
```

The `5.0` value suggest that the imported `import_add_two_f32` function receives 0. Some more tests from [this commit](https://github.com/kajacx/fp-bindgen/commit/3c865da1bda86688817870ccca9fef0e1622a205) also behave like this.

**Used test code:**
Yesterday I created this branch for testing this: https://github.com/kajacx/fp-bindgen/commits/import-f32-problems (only last 4 commits are relevant to this issue).

Today, I stared a new branch by accident, resulting in more tests here: https://github.com/kajacx/fp-bindgen/commits/import-floats-arguments-issues (last 3/5 commits relevant).

**More observations:**
In the [last commit from the second branch](https://github.com/kajacx/fp-bindgen/commit/c50ae25eb1cc5427c35808cd2f7a6a39e2107d36), I tried adding a function with multiple float arguments. It seems only the first one gets zeroed.

This *might* be related to #178, but that issue affected integer primitives as well, this does not. I'm on Windows 10, if it is relevant.

Finally, wrapping the `f32` / `f64` value in a newtype works well.

**Comment by kajacx** [comment]
I tried to reproduce this in wasmer only, and yea, I can confirm this is a bug directly in wasmer 2.3:
https://github.com/kajacx/wasmer-usage

**Comment by arendjr** [comment]
I'm closing this one since it's somewhat out of our control. Best we can do is finish the migration to Wasmer 3 :)
