### ISSUE TITLE
CC linker issues - compilation of generated code on M1 Macbook

### ISSUE THREAD

**Issue by joepio** [fiberplane/fp-bindgen#83]
Hi all! First off: I _love_ what you are doing, such a cool project! I've been hoping something like this would emerge, having played with various WASM runtimes and leaving disappointed with how I could make functions and data cross the host - plugin boundary.

Anyways, I've been trying to [put the example code in my own project](https://github.com/joepio/atomic-data-rust/tree/%2373-fp-bindgen-wasm/lib/src/plugins) (where I want to have a plugin ecosystem), and I think I'm getting close. When I'm trying to compile the runtime, I get this error:

```rs
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-arch" "arm64" "/Users/joep/dev/github/joepio/atomic-data-rust/target/debug/deps/atomic_server-ec888e36e943d493.atomic_server.0aa22211-cgu.0.rcgu.o"
(etc...)
= note: Undefined symbols for architecture arm64:
            "___fp_gen_my_async_imported_function", referenced from:
                atomic_bindings::import::my_async_imported_function::_$u7b$$u7b$closure$u7d$$u7d$::h4e0c2b842a037e5d in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.10.rcgu.o)
            "___fp_gen_make_request", referenced from:
                atomic_bindings::import::make_request::_$u7b$$u7b$closure$u7d$$u7d$::h08afcc77321b9313 in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.10.rcgu.o)
            "___fp_gen_my_plain_imported_function", referenced from:
                atomic_lib::plugins::generated_runtime::bindings::_my_plain_imported_function::h23b36a94db608ae2 in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.3.rcgu.o)
            "___fp_gen_log", referenced from:
                atomic_lib::plugins::generated_runtime::bindings::_log::hbb76c42fdd7eb7bb in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.3.rcgu.o)
            "___fp_gen_my_complex_imported_function", referenced from:
                atomic_lib::plugins::generated_runtime::bindings::_my_complex_imported_function::h024e1af44f660d00 in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.3.rcgu.o)
            "___fp_gen_count_words", referenced from:
                atomic_lib::plugins::generated_runtime::bindings::_count_words::hf570c4e07ff16deb in libatomic_lib-27a5a079070f965e.rlib(atomic_lib-27a5a079070f965e.atomic_lib.a97bb81e-cgu.3.rcgu.o)
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
         
error: could not compile `atomic-server` due to previous error
```

Things I tried:

- `xcode-select --install` helped [some users](https://www.reddit.com/r/rust/comments/i4jlbi/linking_with_cc_failed_exit_code_1/) with similar issues
- as did `cargo install wasm-pack`
- For [others](https://users.rust-lang.org/t/cargo-linking-with-cc-failed-only-when-building-tests/71905) re-installing rust helped: `rustup toolchain uninstall stable && rustup toolchain install stable`.

But not for me. I'm not entirely sure this is the place to post this issue, but maybe you have an idea on how to solve this. Thanks!

**Comment by Zagitta** [comment]
Hello @joepio, thank you for trying out fp-bindgen! 

The issue you're running into is an annoying problem with cargo. As you can see there's a cargo config file in the plugin-example: https://github.com/joepio/atomic-data-rust/blob/%2373-fp-bindgen-wasm/plugin-example/.cargo/config which means if you run `cargo build` within that folder it'll produce a working `wasm32-unknown-unknown` module (meaning you don't have to include `--target wasm32-unknown-unknown` as your readme suggests).
However, if you build the `example-plugin` as part of the workspace cargo ignores that config file and it attempts to build the plugin under your native architecture (`arm64` in your case).

As such the easiest fix is to remove `example-plugin` from your cargo workspace here: https://github.com/joepio/atomic-data-rust/blob/%2373-fp-bindgen-wasm/Cargo.toml#L8 and build the plugin module invidivually.

**Comment by joepio** [comment]
Thanks for the reply @Zagitta !

I have that same `.cargo/config` file in my plugin directory, too. I also tried removing the `example-plugin` from the workspace, but I think the issue I'm describing is unrelated to compiling the plugin - it's a problem with compiling the _runtime_.

**Comment by joepio** [comment]
I think the problem may have been a name mismatch in this: `#[fp(rust_wasmer_runtime_module = "wrong_name")]`

Anyways, the problem is now gone, and I'm currently calling WASM functions from rust :)

**Comment by arendjr** [comment]
I was just looking into your repository. Indeed your runtime code was linking against the bindings that were generated for the plugin, which seems to have been the cause for the linker issues. I think this is a good lesson for our docs/FAQ :)

**Comment by joepio** [comment]
I think a possible solution / direction is to make the entire runtime a generated crate, too. I think it's easier to reason about it that way. Understanding the generated code thing, and knowing how to integrate it into my existing project was the hardest thing for me in setting this up. But anyways, I'm glad it's working now :) definitely worth it.
