### ISSUE TITLE
Not using `fp_bindgen_support`

### ISSUE THREAD

**Issue by joepio** [fiberplane/fp-bindgen#87]
The generated `rust-wasmer-runtime` imports quite a bit from `fp_bindgen_support`, at least in the `example` folder.

But the `fp_bindgen_support` readme clearly states: don't use this directly. But if I want to use the runtime in my app, I have to use `rust-wasmer-runtime/bindings.rs`, which uses `fp_bindgen_support`, which means I still have to import it directly.

Maybe I'm missing something, but I don't know how I can _not_ use this directly as a dependency.

**Comment by arendjr** [comment]
Good question! I think the wording is simply a bit poor. The support crate is intended to be used by generated code, but you generally don’t interact with it directly. So yes, it is correct for your runtime to depend on it. We’ll update the phrasing.

**Comment by joepio** [comment]
Gotcha!

I think this problem, too, would be solved if the generated runtime code is a crate.
